# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-13 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=400)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
