# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_contact_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initial_details',
            name='username',
        ),
    ]
