# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_initial_details_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='initial_details',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
