# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-20 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_initial_details_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('moblie', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
