# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-20 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20170620_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_details',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='basic_details',
            name='moblie',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='basic_details',
            name='profession',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
