# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-20 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20170620_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic_details',
            old_name='moblie',
            new_name='mobile',
        ),
    ]
