# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20170620_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='word_lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('pronounciation', models.CharField(max_length=40)),
                ('hindi', models.CharField(max_length=200)),
                ('english', models.CharField(max_length=200)),
                ('example', models.CharField(max_length=500)),
                ('synonym', models.CharField(max_length=200)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('mnemotrick', models.CharField(max_length=300)),
            ],
        ),
    ]
