# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-23 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_word_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_lists',
            name='english',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='word_lists',
            name='example',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='word_lists',
            name='synonym',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
