# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-23 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20170623_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word_lists',
            old_name='pronounciation',
            new_name='pronunciation',
        ),
    ]
