# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-14 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20170623_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='quest_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('question', models.TextField(blank=True, null=True)),
                ('opt1', models.TextField(blank=True, null=True)),
                ('opt2', models.TextField(blank=True, null=True)),
                ('opt3', models.TextField(blank=True, null=True)),
                ('opt4', models.TextField(blank=True, null=True)),
                ('ans', models.IntegerField()),
            ],
        ),
    ]
