# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-21 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_quest_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('words_completed', models.IntegerField(blank=True, null=True)),
                ('questions_correct', models.IntegerField(blank=True, null=True)),
                ('questions_wrong', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
