# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_user_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_stats',
            name='questions_correct',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user_stats',
            name='words_completed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
