from django.conf.urls import url, include
from .views import (
    main_page,
    signup_page,
    login_page,
    forget_password_page,
    home_page,
    contact_page,
    setting_page,
    upload_words,
    upload_quest,
    request_word,
    request_questions,

    main_file,
    signup_file,
    login_file,
    contact_file,
    setting_file,
    otp_file,
    verify_email,
    verify_otp,
    change_password,
    rough_page,
)

urlpatterns = [
    url(r'^$', main_page),
    url(r'^signup_page/$', signup_page),
    url(r'^login_page/$', login_page),
    url(r'^forget_password_page/$', forget_password_page),
    url(r'^home_page/$', home_page),
    url(r'^contact_page/$', contact_page),
    url(r'^setting_page/$', setting_page),
    url(r'^upload_words/$', upload_words),
    url(r'^upload_quest/$', upload_quest),
    url(r'request_word/$', request_word),
    url(r'request_questions/$', request_questions),

    url(r'^main_file/$', main_file),
    url(r'^signup_file/$', signup_file),
    url(r'^login_file/$', login_file),
    url(r'^contact_file/$', contact_file),
    url(r'^setting_file/$', setting_file),
    url(r'^otp_file/$', otp_file),
    url(r'^verify_email/$', verify_email),
    url(r'^verify_otp/$', verify_otp),
    url(r'^change_password/$', change_password),
    url(r'^rough/$', rough_page),
]
